---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.5
  dataDirHostPath: /var/lib/rook
  network:
    provider: host
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    nodes:
    - name: "k8s-n1"
    - name: "k8s-n2"
    - name: "k8s-n3"
    useAllDevices: true
  placement:
    all:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
