---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: gitea
spec:
  repo: https://dl.gitea.io/charts
  chart: gitea
  valuesContent: |
    memcached:
      enabled: true
    postgresql:
      enabled: true
      persistence:
        enabled: true
    mysql:
      enabled: false
    mariadb:
      enabled: false
    persistence:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: gitea.example.com
          paths:
            - path: /
              pathType: Prefix
    gitea:
      config:
        admin:
          username: gitea_admin
          password: r8sA8CPHD9!bt6d
          email: "gitea@local.domain"
    image:
      repository: gitea/gitea
      tag: "1.16.3"