apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-adapter
  namespace: kube-system
  annotations:
    helm.cattle.io/chart-url: "https://github.com/prometheus-community/helm-charts/releases/download/prometheus-adapter-3.0.2/prometheus-adapter-3.0.2.tgz"
spec:
  bootstrap: true
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-adapter
  version: 3.0.2
  valuesContent: |
    prometheus:
      url: http://monitoring-prometheus.kube-system.svc
    rules:
      resource:
        cpu:
          containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container!=""}[3m])) by (<<.GroupBy>>)
          nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>)
          resources:
            overrides:
              node:
                resource: node
              namespace:
                resource: namespace
              pod:
                resource: pod
          containerLabel: container
        memory:
          containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container!=""}) by (<<.GroupBy>>)
          nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
          resources:
            overrides:
              node:
                resource: node
              namespace:
                resource: namespace
              pod:
                resource: pod
          containerLabel: container
        window: 3m